### ISSUE TITLE
Requesting example of how to use natchez-http4s

### ISSUE THREAD

**Issue by joshm1** [ovotech/effect-utils#42]
I've read all of the source code in the natchez-http4s module, including the test, but I'm struggling with how to use this module in my existing application. 

Any help is greatly appreciated!  Thanks!

**Edit:**

I removed the original code in this post and created the following example project to better show what I'd like to do and the errors I'm having:

https://github.com/joshm1/http4s-playground/blob/master/src/main/scala/Server.scala

**Comment by tomverran** [comment]
Hi,

Looks like from your example you got it working, hope it is going okay!

I am in the process of writing docs (I've actually spent today trying to set up aa microsite!) so hopefully soon there will be some, sorry it has taken me so long to get round to it!

**Comment by Daenyth** [comment]
@tomverran I think he's asking for help with filling out the snippet there - the `???` bits

**Comment by tomverran** [comment]
oh sorry I was probably not super clear - in the repo link @joshm1 added another commit after making this issue that applies the `TraceMiddleware` to the routes: https://github.com/joshm1/http4s-playground/blob/master/src/main/scala/Server.scala#L49

**Comment by joshm1** [comment]
Thanks @tomverran , yes I got my example app working.  I didn't realize there were implicits I could leverage to transform the `IO => `Sync[F] => Kleisli[F, Span[F], *]` for me, if I called the right methods in the right order.  In the commit @tomverran looked at earlier I figured it out by creating 2 different "routes" methods with different implicit contexts in order to get it to work:

```scala
  def _routesWorkingExample[F[_]: Sync]: HttpRoutes[F] = {
    object dsl extends Http4sDsl[F];
    import dsl._
    HttpRoutes.of[F] {
      case GET -> Root / "hello" / name => Ok(name)
    }
  }

  def routes[F[_]: Bracket[*[_], Throwable]](endpoints: Endpoints[F])(
      implicit ev: Sync[Kleisli[F, Span[F], *]]
  ): HttpRoutes[Kleisli[F, Span[F], *]] = _routesWorkingExample

```


However, when I tried to try it with my real app I realized my example app doesn't accurately show what my application looks like.  I actually just pushed an update to my code that tries to do that.  I'm wondering what you'd suggest would be the best way to get this new code to work/compile:

```scala
  def _routesBetterExampleOfRealUseCase[F[_]: Sync](endpoints: Endpoints[F]): HttpRoutes[F] =
    Router(
      "/foo" -> endpoints.foo.service,
      "/bar" -> endpoints.bar.service,
    )

  def routes[F[_]: Bracket[*[_], Throwable]](endpoints: Endpoints[F])(
      implicit ev: Sync[Kleisli[F, Span[F], *]]
  ): HttpRoutes[Kleisli[F, Span[F], *]] = _routesBetterExampleOfRealUseCase(endpoints)
```

error:
```
Error:(38, 121) type mismatch;
 found   : Endpoints[F]
 required: Endpoints[[γ$2$]cats.data.Kleisli[F,natchez.Span[F],γ$2$]]
    (implicit ev: Sync[Kleisli[F, Span[F], *]]): HttpRoutes[Kleisli[F, Span[F], *]] = _routesBetterExampleOfRealUseCase(endpoints)
```

https://github.com/joshm1/http4s-playground/blob/master/src/main/scala/Server.scala#L30-L34

You can ignore example code in original question, I wasn't actually wondering what to put in the `???`. I wrote that before I realized there were implicits in cats and in natchez that would help me.

**Comment by tomverran** [comment]
Hi,

Rather than trying to turn your `HttpApp[F]` into an `HttpApp[Kleisli[F, Span[F], *]` (which is _possible_, just very laborious) I think the best thing to do is to define most of your app with the effect type being `Kleisli[F, Span[F], *]` so that you can directly obtain an `HttpApp[Kleisli[F, Span[F], *]]` from your `_routesBetterExampleOfRealUseCase` function.

Here's an example of what I mean: https://github.com/joshm1/http4s-playground/compare/master...tomverran:traced-routes?expand=1

Creating your routes like this also means you can then use the `Trace` constraint described in the [Natchez readme](https://github.com/tpolecat/natchez/blob/master/README.md) to create subspans, add tags etc in your routes while currently you wouldn't be able to

Hope this makes sense / is helpful!

**Comment by joshm1** [comment]
Thank you, @tomverran! You've been very helpful, I have a much better understanding of how it's supposed to work now (albeit, still trying to figure out some other compiler errors, I'm much further along)

**Comment by tomverran** [comment]
I'll close this issue now as I've finally deployed the microsite which has an example https://ovotech.github.io/effect-utils/docs/natchez-http4s.html :tada:
