### ISSUE TITLE
natchez-datadog submitter stops running after first Span is created, doesn't send to datadog

### ISSUE THREAD

**Issue by joshm1** [ovotech/effect-utils#46]
I noticed that the Stream that checks for queued spans runs every 0.5s, until the first span is created (and I guess being enqueued).  Maybe I'm using this endpoint wrong, but I reproduced this issue in this mini project:

https://github.com/joshm1/http4s-playground/blob/master/src/main/scala/example3/Server.scala

It never called the flatMap function in `submitOnce`:

```scala
  private def submitOnce[F[_]: Sync](client: Client[F], queue: Queue[F, SubmittableSpan]): F[Unit] =
    queue // breakpoint is hit every 0.5s, until I curl my endpoint to create the first span(s)
      .tryDequeueChunk1(maxSize = 1000)
      .flatMap { items => // this function is never invoked
        items.traverse { traces => ... }
      }
      .as(())
```

Issue was noticed by putting a breakpoint in `submitOnce` and seeing that it stopped getting hit after my first `curl localhost:8888/foo` .  Also did some "println debugging" by modifying this line

```scala
.repeatEval(Sync[F].delay(println("tick")) >> sem.acquire >> submitOnce(http, queue) >> sem.release)
```

And I saw "tick" in the console every 0.5s, then it stopped after I ran `curl`. It never called the release function in the resource.

**Comment by tomverran** [comment]
Hi, 

I've just tried your example app and it seems to work for me - do you have the Datadog agent running locally? I suspect if the agent can't be contacted on `http://localhost:8126` the submitter will silently fail - This is something I've been meaning to improve for a while.

If the container is running locally it might be worth checking that you've [enabled the APM](https://docs.datadoghq.com/tracing/send_traces/) - I'm running the agent in a Docker container with the following options to enable the APM, expose the port & allow non local traffic:

```bash
-eDD_APM_ENABLED=true -eDD_APM_NON_LOCAL_TRAFFIC=true -p8126:8126/tcp
```

**Comment by joshm1** [comment]
🤦 🤦 🤦 

I had the agent running. I checked, double checked, and restarted it several times... didn't notice a typo in `-p 8126:8216/tcp`

But yes, it appears the submitter silently fails.  I believe I'll need to make `agentEndpoint` configurable to deploy to kubernetes since my agent is not localhost.  Any suggestion/thoughts on this?  If it reads from an environment variable, `agentEndpoint` wouldn't be "pure".  Anyway, this issue can be closed

**Comment by tomverran** [comment]
I've made a start on supporting a`DD_AGENT_HOST` env var as someone else also asked for it recently & I've also added some error handling to the agent: https://github.com/ovotech/effect-utils/compare/error-handling-and-agent-host

I'll open a PR once I've written some tests, hopefully later today!
